# Generated by Django 3.0.8 on 2020-10-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201005_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
